# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'About Boba'
  items:
  - label: 'Member'
    link: '/about/member'
  - label: 'Contribution'
    link: '/about/contribution'
  - label: 'Recruiting'
    link: '/about/recruiting'
- label: 'Release Note'
  items:
    - label: 'Web App'
      link: '/releases/web'
    - label: 'Kiosk'
      link: '/releases/kiosk'
    - label: 'Homepage'
      link: '/releases/homepage'
    - label: 'iOS App'
      link: '/releases/ios'
    - label: 'Android App'
      link: 'releases/android'
    - label: 'Connector'
      link: 'releases/connector'
    - label: 'Cloud Functions (FaaS)'
      link: 'releases/functions'
    - label: 'Conversion Server'
      link: 'releases/conversion'